import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';

const p=path.join(process.cwd(),'dist','index.html');
let s=await readFile(p,'utf8');
if(!s.includes('VPET_COSA_FACCIO_SE_2026')){
 const css=`<style id="VPET_EMERGENZE_STYLE_2026">
 .emergWrap{border:1px solid #76511d;border-radius:22px;padding:22px;background:linear-gradient(135deg,#10212c,#09141c);color:#fff}.emergHead h3{font:700 28px Georgia,serif;color:#f0b43e;margin:5px 0 8px}.emergHead p{color:#d7dee2;line-height:1.55;max-width:850px}.emergGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px;margin-top:16px}.emergCard{border:1px solid #60461d;border-radius:17px;padding:17px;background:#0f1e28}.emergCard h4{color:#f2ba4c;margin:0 0 8px;font-size:17px}.emergCard p,.emergCard li{color:#d4dce0;font-size:13px;line-height:1.55}.emergCard ol{padding-left:20px;margin:8px 0}.emergCall{border-left:4px solid #eaaa2a;padding:10px 12px;background:#172630;border-radius:10px;margin-top:10px}.emergCall b{color:#f2ba4c}.emergRules{margin-top:14px;border:1px solid #60461d;border-radius:15px;padding:15px;background:#101d25}.emergRules b{color:#f2ba4c}.emergRules p{color:#d4dce0;line-height:1.55;margin:6px 0}.emergSources{font-size:11px;color:#9facb3;margin-top:12px;line-height:1.5}.emergSources a{color:#efbd5b}.emerg112{display:inline-flex;margin-top:10px;border-radius:999px;padding:10px 14px;background:#eaaa2a;color:#171006;text-decoration:none;font-weight:900}@media(max-width:760px){.emergWrap{padding:18px}.emergGrid{grid-template-columns:1fr}.emergHead h3{font-size:25px}}
 </style>`;
 s=s.replace('</head>',css+'</head>');
 const section=`<section class="dashboardExtension" id="VPET_COSA_FACCIO_SE_2026"><div class="emergWrap"><div class="emergHead"><span class="eyebrow2">SICUREZZA • COMPORTAMENTI CORRETTI</span><h3>🐾 Cosa faccio se…?</h3><p>Una guida rapida da consultare quando incontri un animale vagante, ferito, abbandonato o in difficoltà. Prima regola: proteggi te stesso, le altre persone e l'animale; non improvvisare manovre pericolose.</p></div><div class="emergGrid">
 <article class="emergCard"><h4>🐕 Trovo un animale vagante o abbandonato</h4><ol><li>Non inseguirlo e non spaventarlo; osserva da distanza sicura.</li><li>Se puoi farlo senza rischio, annota posizione precisa, direzione e caratteristiche e scatta una foto.</li><li>Segnala il ritrovamento alla Polizia Locale/forze di polizia o al Servizio veterinario ASL competente, che possono attivare le procedure territoriali.</li><li>Non dare per certo che sia abbandonato: potrebbe essersi smarrito.</li></ol><div class="emergCall"><b>Da comunicare:</b> luogo esatto, condizioni dell'animale, pericoli presenti, foto e tuo recapito.</div></article>
 <article class="emergCard"><h4>🩹 Vedo un animale ferito o in grave difficoltà</h4><ol><li>Metti prima in sicurezza la scena, soprattutto vicino al traffico.</li><li>Non avvicinare mani e viso a un animale impaurito o dolorante: può reagire per difesa.</li><li>Contatta il Servizio veterinario ASL e gli organi di polizia competenti; se c'è un pericolo immediato per persone o circolazione usa il numero unico di emergenza.</li><li>Segui le indicazioni dell'operatore prima di spostare l'animale.</li></ol><a class="emerg112" href="tel:112">📞 Emergenza immediata: 112</a></article>
 <article class="emergCard"><h4>🚗 Incidente stradale con un animale</h4><ol><li>Fermati solo dove è possibile farlo in sicurezza e segnala il pericolo agli altri utenti della strada.</li><li>Non creare un secondo incidente tentando un recupero in carreggiata.</li><li>La normativa italiana prevede l'obbligo di fermarsi e di porre in atto ogni misura idonea ad assicurare un tempestivo intervento di soccorso agli animali d'affezione, da reddito o protetti coinvolti.</li><li>Contatta le autorità/servizi competenti e fornisci posizione e condizioni dell'animale.</li></ol><div class="emergCall"><b>Importante:</b> il soccorso dell'animale non deve mettere in pericolo altre persone.</div></article>
 <article class="emergCard"><h4>🚨 Vedo maltrattamento o abbandono</h4><ol><li>Non affrontare direttamente una persona se questo può creare pericolo.</li><li>Annota luogo, ora, descrizione e, solo se possibile legalmente e senza esporti a rischi, conserva elementi utili.</li><li>Segnala tempestivamente alle forze di polizia. In una situazione in corso con rischio immediato chiama il 112.</li><li>Evita di diffondere sui social dati o accuse non verificate: consegna gli elementi alle autorità.</li></ol></article>
 <article class="emergCard"><h4>🪜 Animale bloccato o intrappolato</h4><ol><li>Non arrampicarti, entrare in cunicoli o esporsi a cadute/incendi per recuperarlo.</li><li>Per animali bloccati in situazioni che richiedono soccorso tecnico, come tetti, alberi o cavità, contatta i Vigili del Fuoco.</li><li>Mantieni l'area tranquilla e indica con precisione dove si trova l'animale.</li></ol><div class="emergCall"><b>Soccorso tecnico urgente:</b> 112, che indirizza al servizio competente.</div></article>
 <article class="emergCard"><h4>🦊 Trovo un animale selvatico in difficoltà</h4><ol><li>Non trattarlo come un animale domestico e limita il contatto.</li><li>Non somministrare farmaci o alimenti senza indicazioni specialistiche.</li><li>Contatta le autorità o il centro recupero fauna selvatica competente sul territorio.</li><li>Per pericolo immediato sulla strada o per le persone, chiama il 112.</li></ol></article>
 </div><div class="emergRules"><b>✅ Sane abitudini</b><p>Tieni aggiornati identificazione e recapiti del tuo animale; usa guinzaglio e sistemi di trasporto adeguati; salva sul telefono i riferimenti del veterinario e del Servizio veterinario ASL della tua zona; quando segnali un'emergenza comunica sempre posizione precisa e condizioni osservabili.</p><b>⛔ Cosa evitare</b><p>Inseguire animali spaventati, bloccare il traffico, improvvisare cure, somministrare farmaci umani, pubblicare accuse non verificate o mettere a rischio la propria sicurezza.</p></div><div class="emergSources">Indicazioni generali basate su fonti istituzionali italiane. Le procedure locali possono variare: VPET non sostituisce autorità, veterinari o servizi di emergenza. Fonti: Ministero della Salute — animali d'affezione e possesso responsabile; normativa sul soccorso degli animali coinvolti in incidenti stradali; Vigili del Fuoco per soccorso tecnico. Verifica sempre i riferimenti territoriali aggiornati.</div></div></section>`;
 const marker='<section class="dashboardExtension participaDash"';
 if(s.includes(marker)) s=s.replace(marker,section+'\n\n'+marker); else s=s.replace('</body>',section+'</body>');
}
await writeFile(p,s,'utf8');
console.log('VPET emergency guide applied');
