import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
const out=path.join(process.cwd(),'dist');
const indexPath=path.join(out,'index.html');
let s=await readFile(indexPath,'utf8');

// Make the mobile search real instead of decorative.
s=s.replace('<div class="mpSearch">Cerca servizi, razze, consigli…</div>',`<label class="mpSearchWrap" aria-label="Cerca in VPET"><span aria-hidden="true">⌕</span><input id="vpetGlobalSearch" type="search" inputmode="search" autocomplete="off" placeholder="Cerca servizi, razze, consigli…" aria-label="Cerca servizi, razze e consigli in VPET"><button type="button" id="vpetSearchGo" aria-label="Avvia ricerca">Vai</button></label><div id="vpetSearchResults" class="vpetSearchResults" hidden></div>`);

const css=`<style id="VPET_EXPERIENCE_2026">
:root{--vpet-gold:#f4b83e;--vpet-bg:#02070b;--vpet-panel:#0d171f;--vpet-line:#6b4b1e;--vpet-text:#f7f9fa;--vpet-muted:#c7d0d5}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}
button,a,input{touch-action:manipulation}button,a,[role="button"],input{min-height:44px}button:focus-visible,a:focus-visible,input:focus-visible{outline:3px solid #fff;outline-offset:3px}
.vpetSkip{position:fixed;left:12px;top:-80px;z-index:100000;background:#fff;color:#000;padding:10px 14px;border-radius:10px;font-weight:800}.vpetSkip:focus{top:12px}
.vpetTrust{margin:18px 0 0;border:1px solid #57451f;background:linear-gradient(135deg,#0d171f,#15120d);border-radius:16px;padding:14px 15px;color:#d7dde0;font-size:12px;line-height:1.55}.vpetTrust strong{color:var(--vpet-gold);font-size:13px}.vpetTrust a{color:#ffd56f}
@media(min-width:701px){.hot,.card,button{transition:transform .16s ease,box-shadow .16s ease,border-color .16s ease}.hot:hover,.card:hover{transform:translateY(-2px)}.modal .sheet{max-width:920px}.modal .body{line-height:1.65}.modal .body p{max-width:72ch}}
@media(max-width:700px){
.mobilePhotoDash{padding-bottom:98px!important}.mpTop{position:sticky;top:0;z-index:40;background:linear-gradient(#02070bf2,#02070bdc 80%,transparent);padding:8px 0 10px;backdrop-filter:blur(10px)}
.mpSearchWrap{display:grid;grid-template-columns:28px 1fr auto;align-items:center;gap:8px;border:1px solid #6e5124;border-radius:16px;background:#0d171f;padding:5px 7px 5px 12px;margin-bottom:8px;box-shadow:0 8px 28px #0005}.mpSearchWrap span{font-size:20px;color:#f4b83e}.mpSearchWrap input{width:100%;border:0;background:transparent;color:#fff;font-size:16px;outline:none}.mpSearchWrap input::placeholder{color:#aeb8bd}.mpSearchWrap button{border:1px solid #76541f;border-radius:11px;background:#182733;color:#f4b83e;padding:0 13px;font-weight:900}
.vpetSearchResults{border:1px solid #6e5124;border-radius:16px;background:#071018;padding:7px;margin:-1px 0 12px;box-shadow:0 14px 35px #000a}.vpetSearchResults button{display:flex;width:100%;align-items:center;justify-content:space-between;gap:12px;border:0;border-bottom:1px solid #29343a;background:transparent;color:#fff;text-align:left;padding:10px 9px;font-size:14px}.vpetSearchResults button:last-child{border-bottom:0}.vpetSearchResults b{color:#f4b83e}.vpetSearchEmpty{padding:12px;color:#c5cdd1;font-size:13px}
.mpHero{height:270px!important;box-shadow:0 16px 40px #0009}.mpHero:before{content:'SCOPRI VPET';position:absolute;left:15px;top:15px;z-index:2;background:#05090bd9;border:1px solid #8a6427;border-radius:999px;color:#ffd267;padding:8px 11px;font-size:11px;font-weight:900;letter-spacing:.08em}.mpHero:after{display:block!important;content:'Il mondo pet, tutto in un posto.'!important;bottom:16px!important;font-size:24px!important}
.mpPhoto,.mpQuick button{min-height:160px}.mpPhoto{box-shadow:0 10px 26px #0007}.mpPhoto:active,.mpQuick button:active{transform:scale(.985)}
.mpTitle{display:flex;align-items:center;gap:8px}.mpTitle:after{content:'';height:1px;flex:1;background:linear-gradient(90deg,#6c4b1d,transparent)}
.vpetBottomNav{position:fixed;z-index:9000;left:10px;right:10px;bottom:max(8px,env(safe-area-inset-bottom));display:grid;grid-template-columns:repeat(4,1fr);gap:4px;background:#08131bed;border:1px solid #6d4c1e;border-radius:20px;padding:6px;box-shadow:0 18px 40px #000d;backdrop-filter:blur(16px)}.vpetBottomNav button{border:0;background:transparent;color:#d5dde1;border-radius:14px;font-size:11px;font-weight:800;padding:5px 2px}.vpetBottomNav button span{display:block;font-size:20px;line-height:1.2;color:#f4b83e}.vpetBottomNav button:active{background:#192832}
.vpetBackFloat{bottom:88px!important}.modal .sheet{padding-bottom:100px}.breedTopBack,.vpetEndBack{min-height:48px}
}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{scroll-behavior:auto!important;animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}
</style>`;
if(!s.includes('VPET_EXPERIENCE_2026'))s=s.replace('</head>',css+'</head>');

const nav=`<nav class="vpetBottomNav" aria-label="Navigazione rapida VPET"><button type="button" data-vpet-home><span>⌂</span>Home</button><button type="button" data-vpet-search><span>⌕</span>Cerca</button><button type="button" onclick="openM('sos')"><span>＋</span>SOS</button><button type="button" onclick="openM('near')"><span>⌖</span>Vicino</button></nav>`;
if(!s.includes('vpetBottomNav'))s=s.replace('</body>',nav+'</body>');
const trust=`<div class="vpetTrust" role="note"><strong>VPET informa, non sostituisce il veterinario.</strong><br>Per salute, urgenze, alimentazione clinica o sintomi, verifica sempre con un medico veterinario. I contenuti divulgativi vengono organizzati per essere chiari, consultabili e aggiornabili.</div>`;
if(!s.includes('VPET informa, non sostituisce'))s=s.replace('</body>',trust+'</body>');
if(!s.includes('vpetSkip'))s=s.replace('<body','<a class="vpetSkip" href="#vpet-main">Vai al contenuto</a><body');
s=s.replace('<section class="mobilePhotoDash"','<main id="vpet-main"><section class="mobilePhotoDash"');
if(s.includes('</body>')&&!s.includes('</main><!--vpet-main-->'))s=s.replace('</body>','</main><!--vpet-main--></body>');

const js=`<script id="VPET_EXPERIENCE_JS_2026">(()=>{const items=[['Pet SOS','sos','Emergenze e aiuto'],['Vicino a me','near','Servizi pet nella tua zona'],['Pet Friendly','places','Luoghi e strutture'],['Eventi','events','Eventi e iniziative'],['Viaggia insieme','travel','Guide e viaggi'],['Adozioni','adopt','Trova il tuo amico'],['Guida alle Razze','breeds','Cani e gatti'],['Pet Culture','culture','Cinema, libri e arte'],['Animali nella Storia','history','Storie e curiosità'],['Incredibili insieme','incredibili','Storie che emozionano']];const input=document.getElementById('vpetGlobalSearch'),box=document.getElementById('vpetSearchResults'),go=document.getElementById('vpetSearchGo');function render(){if(!input||!box)return;const q=input.value.trim().toLowerCase();if(!q){box.hidden=true;box.innerHTML='';return}const found=items.filter(x=>(x[0]+' '+x[2]).toLowerCase().includes(q)).slice(0,6);box.hidden=false;box.innerHTML=found.length?found.map(x=>'<button type="button" data-open="'+x[1]+'"><span><b>'+x[0]+'</b><br><small>'+x[2]+'</small></span><span aria-hidden="true">›</span></button>').join(''):'<div class="vpetSearchEmpty">Nessun risultato immediato. Prova con “razze”, “adozioni”, “SOS”, “viaggi” o “eventi”.</div>';box.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{openM(b.dataset.open);box.hidden=true;input.blur()})}function first(){render();const b=box?.querySelector('[data-open]');if(b)b.click()}input?.addEventListener('input',render);input?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();first()}});go?.addEventListener('click',first);document.querySelector('[data-vpet-search]')?.addEventListener('click',()=>{document.getElementById('modal')?.classList.remove('show');window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>input?.focus(),250)});document.querySelector('[data-vpet-home]')?.addEventListener('click',()=>{document.getElementById('modal')?.classList.remove('show');window.scrollTo({top:0,behavior:'smooth'})});document.addEventListener('keydown',e=>{if(e.key==='Escape')document.getElementById('modal')?.classList.remove('show')});})();</script>`;
if(!s.includes('VPET_EXPERIENCE_JS_2026'))s=s.replace('</body>',js+'</body>');

// App-like metadata for Add to Home Screen / PWA packaging.
if(!s.includes('manifest.webmanifest'))s=s.replace('</head>',`<meta name="theme-color" content="#02070b"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><link rel="manifest" href="/manifest.webmanifest"></head>`);
await writeFile(indexPath,s,'utf8');
await writeFile(path.join(out,'manifest.webmanifest'),JSON.stringify({name:'VPET',short_name:'VPET',description:'Informazioni, servizi, storie e strumenti per chi vive con gli animali.',start_url:'/',display:'standalone',background_color:'#02070b',theme_color:'#02070b',icons:[{src:'/vpet-icon.svg',sizes:'any',type:'image/svg+xml',purpose:'any maskable'}]},null,2));
await writeFile(path.join(out,'vpet-icon.svg'),`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><rect width="512" height="512" rx="112" fill="#02070b"/><g fill="#f4b83e"><circle cx="174" cy="173" r="54"/><circle cx="338" cy="173" r="54"/><circle cx="111" cy="282" r="48"/><circle cx="401" cy="282" r="48"/><path d="M256 226c-76 0-133 68-133 137 0 47 36 77 80 64 34-10 72-10 106 0 44 13 80-17 80-64 0-69-57-137-133-137z"/></g></svg>`);
console.log('VPET experience layer applied');