import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
const p=path.join(process.cwd(),'dist','index.html');
let s=await readFile(p,'utf8');

const css=`<style id="VPET_METICULOUS_2026">
:root{--vpet-gold:#f4b83e;--vpet-panel:#10212c;--vpet-line:#76511d;--vpet-muted:#cbd3d7}
.vpetSectionNav{position:sticky;top:0;z-index:10003;display:flex;align-items:center;justify-content:space-between;gap:10px;margin:-16px -16px 14px;padding:12px 16px;background:#08131bf2;border-bottom:1px solid #6d4c1e;backdrop-filter:blur(14px)}
.vpetSectionNav button,.vpetBottomBack{border:1px solid #d99b27;background:#142532;color:#f4b83e;border-radius:999px;padding:11px 15px;font-weight:900;min-height:48px}
.vpetBottomBack{display:block;width:100%;margin:22px 0 4px;font-size:15px}
.vpetBreedTrust{margin:14px 0;border:1px solid #5d461f;border-radius:15px;background:#0d1922;padding:13px;color:#cbd3d7;font-size:12px;line-height:1.55}.vpetBreedTrust b{color:#f4b83e}.vpetBreedTrust a{color:#ffd46d}
.vpetSpeciesGrid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:14px 0}.vpetSpeciesCard{min-height:168px;border:1px solid #76511d;border-radius:20px;padding:17px;background:linear-gradient(145deg,#10212c,#1a241f);color:#fff;text-align:left;position:relative;overflow:hidden}.vpetSpeciesCard:after{content:'›';position:absolute;right:16px;bottom:10px;font-size:34px;color:#f4b83e}.vpetSpeciesCard .ico{font-size:48px;display:block}.vpetSpeciesCard b{display:block;color:#f4b83e;font-size:22px;margin:8px 0 5px}.vpetSpeciesCard small{display:block;color:#cbd3d7;font-size:13px;line-height:1.45}
.vpetCatHero{border:1px solid #76511d;border-radius:22px;padding:21px;background:radial-gradient(circle at 85% 20%,#e5a62e33,transparent 23%),linear-gradient(135deg,#0b1922,#221d16);margin-bottom:14px}.vpetCatHero .eye{color:#f4b83e;font-weight:900;letter-spacing:.14em;font-size:11px}.vpetCatHero h2{font:700 31px Georgia,serif;color:#f4b83e;margin:5px 0 8px}.vpetCatHero p{margin:0;color:#e5eaed;line-height:1.55}
.vpetCatFacts{display:grid;grid-template-columns:1fr 1fr;gap:10px}.vpetCatFact{border:1px solid #5f451d;border-radius:15px;background:#10212c;padding:14px}.vpetCatFact b{display:block;color:#f4b83e;margin-bottom:6px}.vpetCatFact span{color:#dce2e5;line-height:1.5;font-size:14px}.vpetHistoryBox{border-left:4px solid #eaaa2a;background:#151d21;border-radius:12px;padding:14px;margin-top:12px}.vpetHistoryBox b{color:#f4b83e}.vpetHistoryBox p{margin:7px 0 0!important;line-height:1.55}.vpetCatSource{display:flex;flex-wrap:wrap;gap:7px;margin-top:12px}.vpetCatSource a{border:1px solid #66491e;border-radius:999px;padding:7px 10px;color:#ffd46d;text-decoration:none;font-size:12px}
@media(max-width:700px){.modal .sheet{padding-top:16px!important}.vpetSectionNav{top:0}.vpetCatFacts{grid-template-columns:1fr}.vpetSpeciesGrid{grid-template-columns:1fr 1fr}.vpetSpeciesCard{min-height:150px;padding:14px}.vpetSpeciesCard b{font-size:19px}.breedCard{min-height:132px!important}.breedCard b{font-size:18px!important}.breedCard small{font-size:13px!important;line-height:1.45!important}.breedSearch{position:sticky;top:58px;z-index:50;background:#09141c!important;box-shadow:0 9px 20px #0009}.p-breeds{background-size:900% auto!important;background-position:99% 7%!important}.p-history{background-size:900% auto!important;background-position:99% 28%!important}}
@media(max-width:430px){.vpetSpeciesGrid{grid-template-columns:1fr}.vpetSpeciesCard{min-height:126px}.breedGrid{grid-template-columns:1fr!important}}
</style>`;
if(!s.includes('VPET_METICULOUS_2026'))s=s.replace('</head>',css+'</head>');

const js=`<script id="VPET_METICULOUS_JS_2026">(()=>{
const catNames=['Siamese','Maine Coon','Persiano','Bengala','Ragdoll','British Shorthair','Scottish Fold','Sphynx','Norvegese delle Foreste','Siberiano','Abissino','Certosino','Birmano','Burmese','Devon Rex','Cornish Rex','Blu di Russia','Angora Turco','Van Turco','Oriental Shorthair','Exotic Shorthair','American Shorthair','Manx','Bombay'];
const extras={
'Siamese':['Corto, fine, colourpoint','Media','Alta','Molto sociale; soffre facilmente la solitudine prolungata','Controlli veterinari regolari; alcune linee possono avere predisposizioni ereditarie da discutere con il veterinario','Thailandia (antico Siam); è una delle razze feline storiche più note e compare in testimonianze e manoscritti thailandesi.','Gli occhi blu e il contrasto colourpoint sono tratti iconici.'],
'Maine Coon':['Semilungo, fitto e resistente','Grande','Media-alta','Spesso socievole e tollerante; inserimenti sempre graduali','Peso, articolazioni e cuore meritano prevenzione individuale; chiedere screening nelle linee selezionate','Razza naturale nordamericana associata allo Stato del Maine; sulle origini esistono molte leggende, da distinguere dai fatti documentati.','Matura lentamente e può mantenere a lungo un comportamento giocoso.'],
'Persiano':['Lungo e molto folto','Media','Bassa-media','Ama routine tranquille e ambienti prevedibili','Occhi, cute, mantello e respirazione richiedono attenzione, soprattutto nei soggetti brachicefali','Gatti a pelo lungo provenienti dall’area persiana furono introdotti in Europa secoli fa e successivamente selezionati.','La toelettatura quotidiana è parte essenziale del benessere.'],
'Bengala':['Corto, fitto, maculato o marmorizzato','Media','Molto alta','Richiede gioco, arricchimento e possibilità di esplorare','Prevenzione veterinaria e selezione responsabile; energia e curiosità vanno gestite con ambiente adatto','Razza moderna sviluppata nel Novecento con un programma selettivo volto a mantenere aspetto selvatico e comportamento domestico.','Molti soggetti sono attratti dall’acqua e dai giochi interattivi.'],
'Ragdoll':['Semilungo, setoso, colourpoint','Grande','Media','Generalmente orientato alle persone e adatto alla vita familiare','Peso, cuore e apparato urinario vanno monitorati come per ogni individuo; informarsi sugli screening di linea','Razza sviluppata in California negli anni Sessanta.','I Ragdoll colourpoint hanno tipicamente occhi blu.'],
'British Shorthair':['Corto, densissimo','Media-grande','Bassa-media','Calmo e adattabile; spesso apprezza autonomia e routine','Controllo del peso e prevenzione cardiaca/renale secondo indicazione veterinaria','Discende da popolazioni feline britanniche poi selezionate sistematicamente nelle esposizioni.','Il mantello molto fitto crea il tipico aspetto “peluche”.'],
'Scottish Fold':['Corto o semilungo','Media','Media','Dolce e adattabile, ma la scelta deve partire dal benessere','La mutazione delle orecchie è collegata a osteocondrodisplasia: è una questione importante di benessere e selezione responsabile','La piega auricolare deriva da una mutazione comparsa in Scozia nel Novecento.','Le orecchie piegate non sono solo un tratto estetico: hanno implicazioni sanitarie.'],
'Sphynx':['Quasi privo di pelo, con fine peluria','Media','Alta','Molto sociale, curioso e amante del calore','Cute, temperatura, esposizione solare e salute cardiaca richiedono attenzione','La razza moderna deriva da mutazioni naturali senza pelo osservate in Nord America e poi selezionate.','Non è “ipoallergenico” per definizione: gli allergeni felini non dipendono solo dal pelo.'],
'Norvegese delle Foreste':['Semilungo, doppio, resistente','Grande','Media-alta','Equilibrato, arrampicatore, gradisce spazi verticali','Mantello, peso e prevenzione individuale; informarsi su screening di linea','Razza naturale scandinava, adattata a climi rigidi e presente anche nel folklore nordico.','Il doppio mantello idrorepellente è un adattamento tipico.'],
'Siberiano':['Semilungo, triplo mantello','Grande','Media-alta','Affettuoso e attivo; necessita arricchimento','Prevenzione individuale e cura del mantello; nessuna razza è automaticamente adatta alle persone allergiche','Razza naturale russa con lunga storia nelle regioni fredde.','È atletico e spesso eccellente arrampicatore.'],
'Abissino':['Corto con ticking','Media-piccola','Alta','Molto curioso, interattivo e poco sedentario','Peso, denti e prevenzione di routine; informarsi sulla salute delle linee selezionate','Il nome richiama l’Abissinia, ma la ricostruzione delle origini è più complessa e la selezione moderna è britannica.','Il ticking produce una colorazione calda e apparentemente “selvatica”.'],
'Certosino':['Corto, lanoso, blu-grigio','Media-grande','Media','Riservato ma affettuoso; ama routine stabili','Controllo del peso e prevenzione veterinaria','Razza francese storica, descritta in Europa da secoli.','Occhi rame e mantello blu creano il contrasto tipico.'],
'Birmano':['Semilungo, colourpoint con guanti bianchi','Media','Media','Affettuoso, pacato e sociale','Mantello e prevenzione generale; scegliere linee responsabili','La razza è accompagnata da leggende di templi birmani, mentre la selezione europea moderna è documentata nel Novecento.','I “guanti” bianchi sono parte importante dello standard.'],
'Burmese':['Corto e lucido','Media','Alta','Molto orientato alle persone e comunicativo','Prevenzione generale e controllo del peso','Discende da gatti del Sud-est asiatico e fu sviluppato in programmi selettivi statunitensi e britannici.','Tende a mantenere un forte contatto con la famiglia.'],
'Devon Rex':['Corto, ondulato e delicato','Piccola-media','Alta','Estroverso e giocoso','Cute, orecchie e mantello richiedono cure delicate','Deriva da una mutazione naturale osservata nel Devon negli anni Sessanta.','Grandi orecchie e pelo riccio lo rendono immediatamente riconoscibile.'],
'Cornish Rex':['Molto corto e ondulato','Piccola-media','Alta','Energico, socievole e amante del gioco','Protezione dal freddo e cura delicata del mantello','La mutazione del mantello riccio comparve in Cornovaglia nel 1950.','Il mantello è formato soprattutto da pelo molto fine.'],
'Blu di Russia':['Corto, doppio, blu','Media','Media','Riservato con gli estranei, stabile con la famiglia','Routine, peso e prevenzione veterinaria','Associato storicamente al nord della Russia e poi alle esposizioni europee.','Occhi verdi e mantello blu-argento sono distintivi.'],
'Angora Turco':['Semilungo, setoso','Media','Alta','Intelligente e attivo','Cura del mantello; nei bianchi valutare udito secondo indicazione veterinaria','Razza naturale legata ad Ankara e documentata da secoli in Europa.','Alcuni soggetti presentano occhi di colore diverso.'],
'Van Turco':['Semilungo','Grande','Alta','Indipendente, curioso e atletico','Spazio, gioco e gestione del mantello','Associato alla regione del lago di Van, in Turchia orientale.','È celebre come “gatto nuotatore”, ma il comportamento varia da individuo a individuo.'],
'Oriental Shorthair':['Corto, fine, moltissimi colori','Media','Alta','Vocale, sociale e molto interattivo','Prevenzione generale e forte bisogno di stimoli sociali','Sviluppato da linee siamesi con selezione di numerosi colori e pattern.','Condivide la silhouette slanciata e le grandi orecchie del gruppo siamese-orientale.'],
'Exotic Shorthair':['Corto, fitto','Media','Bassa-media','Calmo e affettuoso','Occhi, cute e respirazione vanno monitorati nei soggetti brachicefali','Sviluppato nel Novecento incrociando Persiani con gatti a pelo corto.','È spesso chiamato informalmente “Persiano a pelo corto”.'],
'American Shorthair':['Corto e fitto','Media-grande','Media','Equilibrato e adattabile','Controllo del peso e prevenzione di routine','Discende da gatti arrivati in Nord America con i coloni e poi selezionati negli Stati Uniti.','Storicamente apprezzato anche come cacciatore di roditori.'],
'Manx':['Corto o semilungo','Media','Media-alta','Affettuoso e attivo','La mutazione della coda può associarsi a problemi spinali: selezione e controllo veterinario sono essenziali','Razza storica dell’Isola di Man, nota per la coda ridotta o assente.','Esistono differenti lunghezze di coda all’interno della popolazione.'],
'Bombay':['Corto, nero lucido','Media','Media-alta','Sociale, sicuro e affettuoso','Prevenzione generale, peso e denti','Razza moderna sviluppata negli Stati Uniti per ricordare nell’aspetto una piccola pantera nera.','Mantello nero uniforme e occhi rame sono il suo biglietto da visita.']
};
const originalOpen=window.openM, originalList=window.vpetBreedList, originalDetail=window.vpetBreedDetail;
function sh(){return document.getElementById('sheet')} function show(){document.getElementById('modal')?.classList.add('show')}
function esc(v){return String(v).replace(/[&<>\"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[x]))}
function nav(topFn,topLabel){return '<div class="vpetSectionNav"><button type="button" onclick="'+topFn+'">← '+topLabel+'</button><span style="color:#9eabb2;font-size:12px">VPET</span></div>'}
window.vpetMeticulousBreedHub=function(){const el=sh();if(!el)return;el.innerHTML=nav('closeM()','Dashboard')+'<div class="vpetCatHero"><div class="eye">ENCICLOPEDIA VPET</div><h2>Guida alle Razze</h2><p>Scegli la specie e poi la singola razza. Le schede distinguono caratteristiche tipiche e individualità, con storia, gestione, benessere e fonti da verificare.</p></div><div class="vpetSpeciesGrid"><button class="vpetSpeciesCard" onclick="vpetBreedList(\'cat\')"><span class="ico">🐱</span><b>Gatti</b><small>24 razze feline: ricerca, caratteristiche, cura, storia e curiosità.</small></button><button class="vpetSpeciesCard" onclick="vpetBreedList(\'dog\')"><span class="ico">🐶</span><b>Cani</b><small>18 razze canine già presenti, con schede dedicate.</small></button></div><div class="vpetBreedTrust"><b>Fonti di riferimento.</b> Per le razze feline VPET rimanda agli standard e ai profili di <a href="https://fifeweb.org/cats/breeds/" target="_blank" rel="noopener">FIFe</a> e, dove utile, ai profili <a href="https://tica.org/browse-all-breeds/" target="_blank" rel="noopener">TICA</a>. Salute e comportamento restano individuali e vanno valutati con il veterinario.</div><button class="vpetBottomBack" onclick="closeM()">← Torna alla dashboard</button>';show()};
window.vpetBreedDetail=function(type,i){if(type!=='cat'){return typeof originalDetail==='function'?originalDetail(type,i):undefined}const name=catNames[i],x=extras[name];if(!name||!x)return;const el=sh();el.innerHTML=nav("vpetBreedList('cat')",'Razze di gatti')+'<div class="vpetCatHero"><div class="eye">RAZZA FELINA</div><h2>'+esc(name)+'</h2><p>'+esc(x[0])+' · '+esc(x[2])+' · Attività '+esc(x[3])+'</p></div><div class="vpetCatFacts"><div class="vpetCatFact"><b>Origine / storia</b><span>'+esc(x[6])+'</span></div><div class="vpetCatFact"><b>Mantello</b><span>'+esc(x[0])+'</span></div><div class="vpetCatFact"><b>Taglia</b><span>'+esc(x[1])+'</span></div><div class="vpetCatFact"><b>Attività</b><span>'+esc(x[2])+'</span></div><div class="vpetCatFact"><b>Vita in famiglia</b><span>'+esc(x[3])+'</span></div><div class="vpetCatFact"><b>Salute e prevenzione</b><span>'+esc(x[4])+'</span></div></div><div class="vpetHistoryBox"><b>📜 La sua storia</b><p>'+esc(x[5])+'</p></div><div class="vpetHistoryBox"><b>✨ Curiosità</b><p>'+esc(x[6])+'</p></div><div class="vpetBreedTrust"><b>Come leggere questa scheda.</b> Le caratteristiche di razza descrivono tendenze, non il destino del singolo gatto. Socializzazione, ambiente, salute e storia individuale contano sempre.</div><div class="vpetCatSource"><a href="https://fifeweb.org/cats/breeds/" target="_blank" rel="noopener">FIFe – razze riconosciute ↗</a><a href="https://tica.org/browse-all-breeds/" target="_blank" rel="noopener">TICA – profili razza ↗</a><a href="https://icatcare.org/" target="_blank" rel="noopener">International Cat Care ↗</a></div><button class="vpetBottomBack" onclick="vpetBreedList(\'cat\')">← Torna a Razze di gatti</button>'};
function harden(){
 if(typeof window.openM==='function'&&!window.openM.__vpetMeticulous){const prev=window.openM;const f=function(k){if(k==='breeds')return window.vpetMeticulousBreedHub();return prev.apply(this,arguments)};f.__vpetMeticulous=true;window.openM=f}
 document.querySelectorAll('[onclick*="openM(\'breeds\')"],[aria-label="Guida alle Razze"],[aria-label="Razze"]').forEach(el=>{el.onclick=(e)=>{e?.preventDefault?.();window.vpetMeticulousBreedHub()}});
 const fb=document.getElementById('vpetBackFloat');if(fb)fb.onclick=()=>window.vpetSmartBack();
}
window.vpetSmartBack=function(){const modal=document.getElementById('modal'),el=sh();if(!modal?.classList.contains('show')){window.scrollTo({top:0,behavior:'smooth'});return}const b=el?.querySelector('.vpetSectionNav button,.breedTopBack,.backbtn');if(b){b.click();return}if(typeof closeM==='function')closeM()};
function enhanceSheet(){const el=sh();if(!el)return;const h=(el.querySelector('h2')?.textContent||'').toLowerCase();if(h.includes('guida alle razze')&&!el.querySelector('.vpetSpeciesGrid')&&!el.querySelector('.breedGrid')){window.vpetMeticulousBreedHub();return}if(!el.querySelector('.vpetSectionNav')&&!el.querySelector('.breedTopBack')&&!el.querySelector('.backbtn')){el.insertAdjacentHTML('afterbegin',nav('closeM()','Dashboard'))}if(!el.querySelector('.vpetBottomBack')&&!el.querySelector('.vpetEndBack')){const b=document.createElement('button');b.className='vpetBottomBack';b.textContent='← Torna alla sezione precedente';b.onclick=()=>window.vpetSmartBack();el.appendChild(b)}}
window.addEventListener('DOMContentLoaded',()=>{harden();const el=sh();if(el)new MutationObserver(()=>setTimeout(()=>{harden();enhanceSheet()},0)).observe(el,{childList:true,subtree:false});setTimeout(harden,200);setTimeout(harden,900)});
})();</script>`;
if(!s.includes('VPET_METICULOUS_JS_2026'))s=s.replace('</body>',js+'</body>');
await writeFile(p,s,'utf8');
console.log('VPET meticulous layer applied',s.length);
