import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
const indexPath=path.join(process.cwd(),'dist','index.html');
let s=await readFile(indexPath,'utf8');
const css=`<style id="VPET_POLISH_2026">
@media(max-width:700px){
.mpHero:after{display:none!important}
.mpHero{background-size:205% auto!important;background-position:35% 20%!important}
.mpPhoto:after{content:""!important;position:absolute!important;inset:0!important;background:linear-gradient(180deg,rgba(2,7,11,.72) 0 14%,transparent 30% 52%,rgba(2,7,11,.96) 70% 100%)!important;z-index:1!important;box-shadow:none!important;pointer-events:none!important}
.mpPhoto b,.mpPhoto small{z-index:2!important}
.p-breeds{background-size:620% auto!important;background-position:96% 17%!important}
.vpetBackFloat{position:fixed;left:14px;bottom:86px;z-index:9999;display:none;align-items:center;gap:8px;border:1px solid #d99b27;background:#142532;color:#f4b83e;border-radius:999px;padding:11px 16px;font-weight:900;box-shadow:0 8px 28px #000a}
.modal.show~.vpetBackFloat,.vpetBackFloat.show{display:flex}
.vpetEndBack{width:100%;margin:18px 0 4px;border:1px solid #d99b27;background:#172734;color:#f4b83e;border-radius:14px;padding:14px 16px;font-weight:900;font-size:15px}
.breedHero{border:1px solid #76511d;border-radius:20px;padding:18px;background:linear-gradient(135deg,#102430,#302514);margin-bottom:12px}.breedHero h2{font:700 30px Georgia,serif!important;margin:0 0 8px!important}.breedHero p{margin:0!important}.breedTypeGrid,.breedGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.breedType,.breedCard{border:1px solid #674817;border-radius:16px;background:#10212c;color:#fff;text-align:left;padding:15px}.breedType{min-height:145px}.breedType span{font-size:42px;display:block}.breedType b,.breedCard b{display:block;color:#f5b52d;font-size:17px;margin-top:7px}.breedType small,.breedCard small{display:block;color:#cbd3d7;line-height:1.35;margin-top:5px}.breedSearch{width:100%;border:1px solid #654716;background:#09141c;color:#fff;border-radius:12px;padding:12px 14px;margin:4px 0 12px}.breedCard{min-height:122px}.breedBadge{font-size:28px!important}.breedFacts{display:grid;grid-template-columns:1fr 1fr;gap:9px}.breedFact{border:1px solid #5e431c;background:#10212c;border-radius:14px;padding:13px}.breedFact b{display:block;color:#f5b52d;margin-bottom:5px}.breedFact span{color:#d6dde0;line-height:1.45;font-size:13px}.breedStory{border-left:4px solid #eaaa2a;background:#151d21;border-radius:12px;padding:14px;margin-top:10px}.breedStory b{color:#f5b52d}.breedStory p{margin:6px 0 0!important}.breedNote{font-size:11px;color:#97a3aa;line-height:1.4;margin-top:10px}.breedTopBack{border:1px solid #72501b;background:#111f29;color:#f4b83e;border-radius:999px;padding:9px 13px;font-weight:900;margin-bottom:10px}
}
@media(max-width:430px){.breedTypeGrid,.breedGrid,.breedFacts{grid-template-columns:1fr}}
</style>`;
if(!s.includes('VPET_POLISH_2026'))s=s.replace('</head>',css+'</head>');
const js=`<script id="VPET_POLISH_JS_2026">
(function(){
const cats=[
['Siamese','Thailandia','Affettuoso, vocale, molto sociale','Mantello corto; ama interazione e routine','Tra le razze orientali più antiche e documentate, legata storicamente al Siam.','Gli occhi blu intensi sono uno dei suoi tratti iconici.'],
['Maine Coon','Stati Uniti','Socievole, equilibrato, curioso','Spazzolatura regolare e spazio per muoversi','Razza nordamericana sviluppata nel Maine, circondata da molte leggende sulle sue origini.','È noto per dimensioni importanti e carattere spesso gentile.'],
['Persiano','Area persiana / selezione europea','Tranquillo, dolce, amante della calma','Toelettatura quotidiana e cura di occhi e mantello','I gatti a pelo lungo provenienti dall’area persiana arrivarono in Europa secoli fa.','Il mantello richiede costanza: la bellezza dipende molto dalla cura.'],
['Bengala','Stati Uniti','Attivo, intelligente, esploratore','Arricchimento ambientale, gioco e movimento','Razza moderna selezionata per un aspetto maculato che ricorda i felini selvatici.','Spesso ama l’acqua più di molti altri gatti domestici.'],
['Ragdoll','Stati Uniti','Dolce, rilassato, orientato alle persone','Spazzolatura e vita familiare stabile','Selezionato in California negli anni Sessanta per temperamento docile e aspetto imponente.','Il nome richiama la tendenza di alcuni soggetti a rilassarsi quando vengono presi in braccio.'],
['British Shorthair','Regno Unito','Calmo, indipendente ma affettuoso','Controllo del peso e gioco regolare','Deriva da antiche popolazioni feline britanniche poi selezionate in modo sistematico.','La testa rotonda e il mantello fitto sono tra i segni più riconoscibili.'],
['Scottish Fold','Scozia','Dolce, curioso, adattabile','Gestione attenta e controlli veterinari responsabili','La caratteristica piega delle orecchie deriva da una mutazione comparsa in Scozia nel Novecento.','La selezione va affrontata con particolare attenzione al benessere articolare.'],
['Sphynx','Canada','Socievole, caldo, molto presente','Cura della pelle e protezione da freddo e sole','La razza moderna nasce da mutazioni naturali selezionate in Canada.','Non è davvero completamente “senza pelo”: spesso presenta una finissima peluria.'],
['Norvegese delle Foreste','Norvegia','Equilibrato, agile, indipendente','Spazzolatura soprattutto nei cambi di stagione','Gatto nordico adattato a climi rigidi, legato anche al folklore scandinavo.','Il doppio mantello è una delle sue grandi risorse naturali.'],
['Siberiano','Russia','Affettuoso, robusto, giocherellone','Spazzolatura e attività fisica','Razza naturale russa con lunga presenza nelle regioni fredde.','È un ottimo arrampicatore e conserva una struttura atletica.'],
['Abissino','Origini discusse; selezione britannica','Attivo, curioso, molto intelligente','Gioco quotidiano e ambiente ricco','Il nome richiama l’Abissinia, ma la storia genetica e selettiva è più complessa.','Il pelo ticking gli dona un aspetto caldo e particolare.'],
['Certosino','Francia','Riservato, dolce, equilibrato','Spazzolatura semplice e controllo del peso','Razza francese storica, citata da secoli nella cultura europea.','Il mantello blu-grigio e gli occhi rame creano un forte contrasto.'],
['Birmano','Origini leggendarie asiatiche; selezione europea','Affettuoso, pacato, sociale','Spazzolatura regolare','La razza è accompagnata da una famosa leggenda legata ai templi birmani.','Le zampe bianche “a guanto” sono un tratto caratteristico.'],
['Burmese','Sud-est asiatico / selezione USA-UK','Vivace, affettuoso, comunicativo','Molto contatto umano e gioco','Discende da gatti del Sud-est asiatico poi selezionati nel Novecento.','Tende a creare un rapporto molto stretto con la famiglia.'],
['Devon Rex','Regno Unito','Estroverso, buffo, affettuoso','Cura delicata di pelle e mantello','Nato da una mutazione naturale comparsa nel Devon negli anni Sessanta.','Le grandi orecchie e il pelo riccio gli danno un aspetto inconfondibile.'],
['Cornish Rex','Regno Unito','Energico, giocoso, socievole','Protezione dal freddo e attività','La mutazione del mantello riccio comparve in Cornovaglia nel 1950.','Ha un mantello molto diverso dalla maggior parte delle razze feline.'],
['Blu di Russia','Russia / Europa del Nord','Riservato, elegante, fedele','Routine tranquilla e gioco moderato','Associato storicamente ai porti del nord della Russia e poi alle esposizioni europee.','Il doppio mantello blu e gli occhi verdi sono distintivi.'],
['Angora Turco','Turchia','Elegante, attivo, intelligente','Spazzolatura e stimoli','Razza naturale legata alla regione di Ankara, storicamente apprezzata per il pelo setoso.','Alcuni soggetti bianchi possono avere occhi di colore diverso.'],
['Van Turco','Turchia','Energico, indipendente, curioso','Spazio, gioco e gestione del mantello','Associato alla regione del lago di Van.','È celebre per la fama di “gatto nuotatore”, anche se ogni individuo è diverso.'],
['Oriental Shorthair','Regno Unito','Vocale, affettuoso, molto attivo','Interazione costante e gioco','Sviluppato a partire da linee siamesi con grande varietà di colori.','Ha una silhouette slanciata e grandi orecchie.'],
['Exotic Shorthair','Stati Uniti','Calmo, affettuoso, tranquillo','Cura di occhi e pieghe del muso','Selezionato incrociando Persiani con gatti a pelo corto.','Viene spesso descritto come un “Persiano a pelo corto”.'],
['American Shorthair','Stati Uniti','Equilibrato, adattabile, robusto','Gioco, controllo del peso','Discende da gatti portati dai coloni e poi selezionati negli Stati Uniti.','Storicamente apprezzato anche per l’abilità nella caccia ai roditori.'],
['Manx','Isola di Man','Affettuoso, robusto, attivo','Attenzione alla colonna e selezione responsabile','Razza storica dell’Isola di Man famosa per la coda ridotta o assente.','La caratteristica della coda deriva da una mutazione genetica.'],
['Bombay','Stati Uniti','Affettuoso, sicuro, sociale','Gioco e compagnia','Razza moderna selezionata per ricordare una piccola pantera nera.','Mantello nero lucido e occhi ramati sono il suo biglietto da visita.']
];
const dogs=[
['Labrador Retriever','Canada / Regno Unito','Socievole, collaborativo, energico','Movimento, peso sotto controllo, attività mentale','Discende dai cani da lavoro di Terranova poi selezionati in Gran Bretagna.','È tra le razze più utilizzate anche in assistenza e ricerca.'],
['Golden Retriever','Regno Unito','Dolce, collaborativo, attivo','Movimento, spazzolatura, attività condivise','Selezionato in Scozia nell’Ottocento come cane da riporto.','Spesso eccelle nei lavori di relazione con le persone.'],
['Pastore Tedesco','Germania','Intelligente, vigile, versatile','Educazione coerente e attività','Razza sviluppata a fine Ottocento per lavoro e conduzione.','La sua versatilità lo ha reso protagonista in moltissimi compiti.'],
['Border Collie','Regno Unito','Intensissimo, brillante, sensibile','Molto lavoro mentale e attività','Selezionato nelle regioni di confine tra Scozia e Inghilterra per la conduzione delle greggi.','È celebre per la capacità di apprendimento.'],
['Beagle','Regno Unito','Socievole, curioso, determinato','Fiuto, passeggiate e gestione del richiamo','Razza da seguita con lunga tradizione britannica.','Il naso guida molte delle sue decisioni.'],
['Bulldog Francese','Francia','Affettuoso, vivace, urbano','Attenzione al caldo e attività moderata','Sviluppato in Francia da piccoli bulldog portati anche da lavoratori inglesi.','La respirazione va sempre tutelata con gestione prudente.'],
['Barboncino','Europa','Intelligente, attivo, sensibile','Toelettatura e stimoli mentali','Antico cane d’acqua europeo, poi diventato anche cane da compagnia.','Il mantello riccio cresce continuamente e richiede cura.'],
['Chihuahua','Messico','Vivace, vigile, molto legato','Protezione dal freddo e socializzazione','Associato storicamente al Messico e a piccoli cani precolombiani.','È tra le razze canine di taglia più piccola.'],
['Bassotto','Germania','Coraggioso, curioso, tenace','Peso sotto controllo e protezione della schiena','Selezionato per il lavoro in tana.','Il corpo allungato richiede particolare attenzione alla colonna vertebrale.'],
['Jack Russell Terrier','Regno Unito','Energico, tenace, brillante','Attività intensa e regole chiare','Nato dalla selezione di terrier da lavoro del reverendo John Russell.','Piccolo di taglia, enorme per energia.'],
['Shiba Inu','Giappone','Indipendente, pulito, vigile','Socializzazione e gestione coerente','Antica razza giapponese da caccia.','È famoso per espressività e forte personalità.'],
['Akita Inu','Giappone','Fiero, leale, riservato','Socializzazione precoce e gestione esperta','Razza giapponese antica legata alla prefettura di Akita.','La storia di Hachikō ha reso celebre nel mondo la sua lealtà.'],
['Siberian Husky','Siberia','Socievole, atletico, indipendente','Molto movimento e clima gestito','Selezionato dai popoli ciukci per traino e resistenza.','È costruito per percorrere grandi distanze.'],
['Maltese','Mediterraneo','Affettuoso, vivace, da compagnia','Cura del mantello e denti','Piccoli cani bianchi simili sono rappresentati da secoli nell’area mediterranea.','Il mantello lungo richiede molta manutenzione.'],
['Cavalier King Charles Spaniel','Regno Unito','Dolce, sociale, adattabile','Compagnia, movimento moderato, controlli veterinari','Discende dai piccoli spaniel raffigurati nelle corti britanniche.','È fortemente orientato alla vita con le persone.'],
['Boxer','Germania','Energico, affettuoso, giocoso','Attività, educazione, attenzione al caldo','Razza tedesca sviluppata a fine Ottocento.','Conserva spesso un carattere molto giocoso anche da adulto.'],
['Cocker Spaniel Inglese','Regno Unito','Allegro, sensibile, attivo','Orecchie, mantello e movimento','Selezionato come cane da cerca e riporto nel Regno Unito.','Il nome è legato storicamente alla caccia alla beccaccia.'],
['Alano','Germania','Gentile, imponente, tranquillo','Spazio, crescita controllata, gestione articolare','Grande razza europea sviluppata da antichi cani da caccia e guardia.','Nonostante la mole viene spesso descritto come molto affettuoso.']
];
function sh(){return document.getElementById('sheet')}
function openBox(){const m=document.getElementById('modal');if(m)m.classList.add('show')}
function esc(v){return String(v).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
function navEnd(label,fn){return '<button class="vpetEndBack" onclick="'+fn+'">← '+label+'</button>'}
window.vpetBreedHub=function(){const el=sh();if(!el)return;el.innerHTML='<button class="breedTopBack" onclick="closeM()">← Dashboard</button><div class="breedHero"><div class="eyebrow2">ENCICLOPEDIA VPET</div><h2>Guida alle Razze</h2><p>Scegli cani o gatti. Ogni scheda raccoglie origine, carattere, cura, storia e curiosità.</p></div><div class="breedTypeGrid"><button class="breedType" onclick="vpetBreedList(\'cat\')"><span>🐱</span><b>Razze di gatti</b><small>24 razze con schede approfondite.</small></button><button class="breedType" onclick="vpetBreedList(\'dog\')"><span>🐶</span><b>Razze di cani</b><small>18 razze con storia e consigli pratici.</small></button></div>'+navEnd('Torna alla dashboard','closeM()');openBox()}
window.vpetBreedList=function(type){const data=type==='cat'?cats:dogs;const title=type==='cat'?'Razze di gatti':'Razze di cani';const el=sh();el.innerHTML='<button class="breedTopBack" onclick="vpetBreedHub()">← Guida alle Razze</button><div class="breedHero"><h2>'+title+'</h2><p>Tocca una razza per aprire la sua scheda completa.</p></div><input class="breedSearch" placeholder="Cerca una razza…" oninput="vpetFilterBreeds(this.value)"><div class="breedGrid" id="breedGrid">'+data.map((b,i)=>'<button class="breedCard" data-name="'+esc(b[0].toLowerCase())+'" onclick="vpetBreedDetail(\''+type+'\','+i+')"><span class="breedBadge">'+(type==='cat'?'🐱':'🐶')+'</span><b>'+esc(b[0])+'</b><small>'+esc(b[1])+' · '+esc(b[2])+'</small></button>').join('')+'</div>'+navEnd('Torna a Guida alle Razze','vpetBreedHub()')}
window.vpetFilterBreeds=function(q){q=q.toLowerCase().trim();document.querySelectorAll('#breedGrid .breedCard').forEach(x=>x.style.display=!q||x.dataset.name.includes(q)?'block':'none')}
window.vpetBreedDetail=function(type,i){const data=type==='cat'?cats:dogs,b=data[i];if(!b)return;const el=sh();const back="vpetBreedList('"+type+"')";el.innerHTML='<button class="breedTopBack" onclick="'+back+'">← '+(type==='cat'?'Gatti':'Cani')+'</button><div class="breedHero"><div class="eyebrow2">VPET EXPERIENCE</div><h2>'+esc(b[0])+'</h2><p>'+esc(b[1])+'</p></div><div class="breedFacts"><div class="breedFact"><b>Carattere</b><span>'+esc(b[2])+'</span></div><div class="breedFact"><b>Cura e gestione</b><span>'+esc(b[3])+'</span></div><div class="breedFact"><b>Vita in famiglia</b><span>Valuta sempre spazio, tempo, attività e compatibilità con persone e altri animali.</span></div><div class="breedFact"><b>Benessere</b><span>Controlli veterinari periodici, peso adeguato e osservazione dei cambiamenti individuali.</span></div></div><div class="breedStory"><b>📜 La sua storia</b><p>'+esc(b[4])+'</p></div><div class="breedStory"><b>✨ Curiosità</b><p>'+esc(b[5])+'</p></div><div class="detailBlock"><h4>Prima di scegliere questa razza</h4><p>Lo standard descrive tendenze tipiche, ma ogni animale è un individuo. Valuta provenienza responsabile, salute, socializzazione, ambiente, costi e tempo disponibile.</p></div><div class="breedNote">Le informazioni VPET hanno finalità divulgativa e non sostituiscono il parere del veterinario o di un professionista qualificato.</div>'+navEnd('Torna a '+(type==='cat'?'Razze di gatti':'Razze di cani'),back)}
window.addEventListener('DOMContentLoaded',()=>{
 const modal=document.getElementById('modal'),sheet=document.getElementById('sheet');
 const fb=document.createElement('button');fb.className='vpetBackFloat';fb.id='vpetBackFloat';fb.innerHTML='← Torna indietro';fb.onclick=()=>{if(modal&&modal.classList.contains('show'))closeM()};document.body.appendChild(fb);
 if(modal)new MutationObserver(()=>fb.classList.toggle('show',modal.classList.contains('show'))).observe(modal,{attributes:true,attributeFilter:['class']});
 if(sheet)new MutationObserver(()=>{if(!sheet.querySelector('.vpetEndBack')){const b=document.createElement('button');b.className='vpetEndBack';b.textContent='← Torna alla dashboard';b.onclick=()=>closeM();sheet.appendChild(b)}}).observe(sheet,{childList:true,subtree:false});
 const old=window.openM;if(typeof old==='function'){window.openM=function(k){if(k==='breeds')return vpetBreedHub();return old.apply(this,arguments)}}
});
})();
</script>`;
if(!s.includes('VPET_POLISH_JS_2026'))s=s.replace('</body>',js+'</body>');
await writeFile(indexPath,s,'utf8');
console.log('VPET polish complete',s.length);
